---
title: "NCBI eukaryotes info"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    df_print: paged
    highlight: espresso
    number_sections: yes
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: yes
---
# Packages
```{r message=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(igraph)
library(tidylog)
library(magrittr)
```

# Loading data
```{r message=FALSE}
taxid_hierarchy <- read_delim(
  "download/taxonomy/nodes.dmp",
  skip = 1,
  delim = "|",
  trim_ws = TRUE,
  col_names = c("taxid","hierarchy"),
  col_types = cols_only("i", "-", "c")
)

ncbi_taxon_names <- read_delim(
  "download/taxonomy/names.dmp",
  delim = "|",
  trim_ws = TRUE,
  col_names = c("taxid","ncbi_name","type"),
  col_types = cols_only("i", "c", "-", "c")
)
```

# Finding duplicated genera in the whole ncbi database
```{r}
# leaving only genera nodes
taxid_hierarchy %<>% filter(hierarchy == "genus")

# leaving only scientific names
ncbi_taxon_names %<>%
  filter(type == "scientific name") %>%
  select(taxid, ncbi_name) %>%
  inner_join(taxid_hierarchy)

duplicated_genera <- ncbi_taxon_names[duplicated(ncbi_taxon_names$ncbi_name),] %>% pull(ncbi_name)

write(duplicated_genera, file = "duplicated_genera.txt")
```
