---
title: "NCBI eukaryotes info"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    df_print: paged
    highlight: espresso
    number_sections: yes
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: yes
---
# Packages
```{r message=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(igraph)
library(tidylog)
library(magrittr)
```

# Downloading files
```{r message=FALSE}
if (!file.exists("download/taxonomy")) {
  tmp <- tempfile()
  download.file("https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz", tmp)
  untar(tmp, exdir = "download/taxonomy")
  unlink(tmp)
}

if (!file.exists("download/species.v11.0.txt")) {
  download.file("https://stringdb-static.org/download/species.v11.0.txt", "download/species.v11.0.txt")
}
```

# Loading data
```{r message=FALSE}
string_species <- read_tsv(
  "download/species.v11.0.txt",
  skip = 1,
  col_names = c("taxid", "string_name"),
  col_types = cols_only("c", "-", "c")
)

ncbi_merged_ids <- read_delim(
  "download/taxonomy/merged.dmp",
  delim = "|",
  trim_ws = TRUE,
  col_names = c("taxid","new_taxid"),
  col_types = cols_only("c", "c")
)

ncbi_edgelist <- read_delim(
  "download/taxonomy/nodes.dmp",
  skip = 1,
  delim = "|",
  trim_ws = TRUE,
  col_names = c("n1","n2"),
  col_types = cols_only("i", "i")
)

ncbi_taxon_names <- read_delim(
  "download/taxonomy/names.dmp",
  delim = "|",
  trim_ws = TRUE,
  col_names = c("name","ncbi_name","type"),
  col_types = cols_only("i", "c", "-", "c")
)
```

# Creating graph
```{r}
# leaving only scientific names
ncbi_taxon_names %<>%
  filter(type == "scientific name") %>%
  select(node, ncbi_name)

# finding Eukaryota taxid
eukaryota_taxon_id <- subset(ncbi_taxon_names, ncbi_name == "Eukaryota", "name", drop = TRUE)

# updating string taxids
string_species %<>%
  left_join(ncbi_merged_ids) %>%
  mutate(new_taxid = coalesce(new_taxid, taxid))

# creating graph
g <- graph_from_data_frame(ncbi_edgelist[,2:1], directed = TRUE, vertices = ncbi_taxon_names)

# easing memory
rm(ncbi_edgelist, ncbi_merged_ids)
```

# Traversing graph from the "Eukaryota" node to its leaves
```{r}
eukaryote_root <- V(g)[eukaryota_taxon_id]
eukaryote_leaves <- V(g)[string_species[["new_taxid"]]]

# not_found <- subset(string_species, !new_taxid %in% ncbi_taxon_names$name)

eukaryote_paths <- shortest_paths(g, from = eukaryote_root, to = eukaryote_leaves, mode = "out")$vpath

eukaryote_vertices <- eukaryote_paths %>% unlist %>% unique

eukaryote_tree <- induced_subgraph(g, eukaryote_vertices, impl = "create_from_scratch")
```

# Saving
```{r}
# ncbi_tree <- ape::as.phylo(get.edgelist(eukaryote_tree)) %>% ape::ladderize()
ncbi_tree <- treeio::as.phylo(eukaryote_tree)

# plot(ncbi_tree %>% ape::ladderize(), type="cladogram")

string_eukaryotes <- string_species %>%
  filter(new_taxid %in% ncbi_tree$tip.label) %>%
  inner_join(ncbi_taxon_names, by = c("new_taxid" = "name"))

write.table(string_eukaryotes[,"ncbi_name"],"476_ncbi_eukaryotes.txt", col.names = F, row.names = F, quote = F)

usethis::use_data(ncbi_tree, overwrite = TRUE)
usethis::use_data(string_eukaryotes, overwrite = TRUE)

```
