---
title: "Expression neuroexclusivity"
output:
  html_document:
    df_print: paged
    theme: default
    highlight: espresso
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---
# Objectives
Compile multiple expression data downloaded from gxa into `n11_expression.tsv`.
```{r message=FALSE}
library(tidyverse)
library(magrittr)

data(gene_ids, package = "neurotransmission")
```

# Downloading experiment data
```{r message=FALSE}
experiments <- c(
  "E-MTAB-513",
  "E-MTAB-2836",
  # "E-MTAB-2919",
  "E-MTAB-3358",
  "E-MTAB-3708",
  "E-MTAB-3716",
  "E-MTAB-4344",
  "E-MTAB-4840",
  "E-MTAB-5214"
)

for(experiment in experiments) {
  if (!file.exists(paste0("download/gxa/", experiment, ".tsv"))) {
    download.file(
      paste0("https://www.ebi.ac.uk/gxa/experiments-content/", experiment, "/resources/ExperimentDownloadSupplier.RnaSeqBaseline/tpms.tsv"),
      paste0("download/gxa/", experiment, ".tsv")
    )
  }
}
```

# Data
Loading all expression data files contained in the `dados/gxa` folder.
```{r message=FALSE}
expression_data <- sapply(
  list.files("download/gxa/", full.names = T),
  read_tsv,
  comment = "#",
  simplify = FALSE,
  USE.NAMES = TRUE
)
```

# Reshaping
```{r}
expression_data %<>%
  lapply(pivot_longer, cols = -(1:2), names_to = "tissue", values_to = "tpm") %>%
  bind_rows %>%
  na.omit %>%
  select(ensembl_id = `Gene ID`, tissue, tpm)
```

# Cleaning
```{r}
# E-MTAB-4840 has comma separated developmental stage info (removing evrthng before ", ")
expression_data %<>% mutate(tissue = str_remove(tissue, "^.+, "))

# expression_data %>% pull(tissue) %>% unique %>% sort

tissue_names_fix <- c(
  "brain fragment"                     = "brain",
  "forebrain fragment"                 = "forebrain",
  "forebrain and midbrain"             = "forebrain",
  "hindbrain fragment"                 = "hindbrain",
  "hindbrain without cerebellum"       = "hindbrain",
  "hippocampus proper"                 = "hippocampus",
  "hippocampal formation"              = "hippocampus",
  "diencephalon and midbrain"          = "diencephalon",
  "visceral (omentum) adipose tissue"  = "adipose tissue",
  "subcutaneous adipose tissue"        = "adipose tissue",
  "spinal cord (cervical c-1)"         = "spinal cord",
  "C1 segment of cervical spinal cord" = "spinal cord"
)

expression_data %<>% mutate(tissue = recode(tissue, !!!tissue_names_fix))
           
#subseting for speed
expression_data %<>% filter(ensembl_id %in% gene_ids[["ensembl_id"]])

# writing temp annotation
expression_data %>%
  select(tissue) %>%
  unique %>%
  arrange %>%
  mutate(is_nervous = NA) %>%
  write_tsv("temp_tissue_classification.tsv")

# usethis::use_data(expression_data, overwrite = TRUE)
```

# loading manual classification
```{r}
tissue_classification <- read_tsv("tissue_classification.tsv", col_types = "ci")
```

# Maths
```{r}
avg_by_tissue <- expression_data %>%
  group_by(ensembl_id, tissue) %>%
  summarise(tpm_avg = mean(tpm))

#attaching neural tissue information
avg_by_tissue %<>% left_join(tissue_classification)

#measuring neuroexclusivity
expression_neuroexclusivity <- avg_by_tissue %>%
  filter(tpm_avg >= 0.5) %>%
  group_by(ensembl_id) %>%
  summarise(expression_neuroexclusivity = sum(tpm_avg[is_nervous == 1])/sum(tpm_avg))

# exporting for package use
usethis::use_data(expression_neuroexclusivity, overwrite = TRUE)
```
