---
# layout: 12pt,review
linenumbers: true
title: "Ionotropic receptors as the driving force behind human synapse establishment"
subtitle: "Supplementary Material"
author: 
  - Lucas H. Viscardi
  - Danilo O. Imparato
  - Maria Cátira Bortolini
  - Rodrigo J. S. Dalmolin
abstract: |
  Model uncertainty and limited data are fundamental challenges to
  robust management of human intervention in a natural system.
  These challenges are acutely highlighted by concerns that
  many ecological systems may contain tipping points, such as
  Allee population sizes.  Before a collapse, we do not know
  where the tipping points lie, if they exist at all.  Hence,
  we know neither a complete model of the system dynamics nor
  do we have access to data in some large region of state-space
  where such a tipping point might exist.
  
keywords:
  - Evolution
  - Nervous system
  
# header-includes:
   # - \usepackage[table]{xcolor}
   # - \usepackage{docmute}
   # - \usepackage{float}
   # - \usepackage{booktabs}
   
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}

## rmarkdown render options
output:
  pdf_document:
    toc: yes
    toc_depth: 3
    highlight: zenburn
    # pandoc_args: "--highlight=breezedark"
    # fig_caption: true
    # template: components/elsarticle.latex
    keep_tex: false
---

<!--- Project structure -->
**Project structure**
=====================
This is the title page

**Preprocessing**
=================
This topic refers mainly to data wrangling done before the actual analysis with the intent of making it simpler.

<!--- Eukaryota species tree -->
**Eukaryota species tree**
--------------------------
We opted to use the TimeTree database in order to obtain an standardized Eukaryota species tree. However, some species were not present in it, so we devised a way to fill them in based on NCBI Taxonomy data. 

### NCBI Taxonomy tree
First we preprocess NCBI Taxonomy data to leave only STRING eukaryotes, thus making the task easier.
\input{tree_ncbi.tex}
<!-- \input{download_files.tex} -->

### Duplicated Genera
Some species from different kingdoms may share the same genus name. These genera must be noted down because one of the ways we fill in missing species is by looking at genera names.

### Hybrid tree
Explanation

<!--- Kegg annotation -->
**Gene selection and annotation**
---------------------------------

<!--- Kegg annotation -->
**Gene selection and annotation**
---------------------------------

<!--- Neuroexclusivity -->
**Neuroexclusivity**
--------------------
Explanation

### Expression

### Pathways

<!--- COG data -->
**COG data**
------------

<!--- Network -->
**Network**
-----------

**Analysis**
============
Analysis

```{r setup}
library(magrittr)
library(neurotransmissionevolution)
```

<!-- \input{download_files.tex} -->

Test tab2
```{r}
tibble::tribble(
  ~col_name,   ~col_type, ~used, ~ex,                  ~desc,
  "string_id", "numeric", "yes", "9606.ENSP000000666", "This represents the string protein identifier.",
  "length",    "numeric", "yes", "666",                "This represents the protein size"
) %>% print_dataframe_specification("a", "b", "caption")
```

