---
title: "Abundance"
knit: neurotransmissionevolution::custom_knit
---
```{r include=FALSE}
knitr::opts_chunk$set(
  warning     = FALSE,
  message     = FALSE,
  cache       = TRUE#,
  # cache.extra = file.mtime("download/link_pathway_entrez.tsv")
)
```

Loading initial resources:
```{r}
# Data manipulation
library(tidyverse)
library(magrittr)

# Utils
library(neurotransmissionevolution)

# Packaged data
data(
   cogs
  ,gene_ids
  ,gene_cogs
  ,string_eukaryotes
  ,package = "neurotransmissionevolution"
)

# Fresh analysis data
cog_roots                   <- read_tsv("geneplast_roots.tsv",             col_types = "ci")
clade_names                 <- read_tsv("geneplast_clade_names.tsv",       col_types = "ic")
clade_taxids                <- read_tsv("geneplast_clade_taxids.tsv",      col_types = "ici")

# Collapsing similar functions
gene_annotation <- read_tsv("../data/gene_annotation.tsv", col_types = "cc") %>%
  mutate(annotation = case_when(
     grepl("clearance",   annotation) ~ "depletion"
    ,grepl("degradation", annotation) ~ "depletion"
    ,grepl("transport",   annotation) ~ "synthesis"
    ,TRUE ~ annotation
  ))
```

A
```{r}
# If a gene has more than 1 COG, select the oldest one.
# This is unusual, but can happen in cases of gene fusion, for instance.
gene_cogs %<>%
  inner_join(cog_roots) %>%
  group_by(string_id) %>%
  filter(root == max(root))

# The function of a COG is the function of its proteins
cog_annotation <- gene_ids %>%
  inner_join(gene_cogs) %>%
  inner_join(gene_annotation) %>%
  distinct(cog_id, annotation)

# Number of proteins in a COG in every species
cog_size_by_taxid <- cogs %>%
  filter(cog_id %in% gene_cogs[["cog_id"]]) %>%
  count(taxid, cog_id, name = "cog_size")

# Number of COGs in every species
cog_n_by_taxid <- cog_size_by_taxid %>%
  count(taxid, name = "cog_n")

# Number of proteins in every species
protein_n_by_taxid <- cog_size_by_taxid %>%
  count(taxid, wt = cog_size, name = "protein_n")

# Mapping species to clade info
ordered_species <- string_eukaryotes %>%
  select(taxid, ncbi_name) %>%
  left_join(clade_taxids) %>%
  left_join(clade_names, by = c("lca" = "root")) %>%
  mutate(
     lca        = as_factor(lca) %>% fct_rev
    ,ncbi_name  = fct_reorder(ncbi_name, -taxid_order)
    ,clade_name = fct_reorder(clade_name, -taxid_order)
  )

annotation_colors <- c(
   "depletion"             = "#F40000"
  ,"excitability"          = "#FFAB00"
  ,"receptor-associated"   = "#D6EE00"
  ,"ionotropic receptor"   = "#43FF1C"
  ,"metabotropic receptor" = "#18FFFF"
  ,"signaling"             = "#0091EA"
  ,"g-protein"             = "#0033ff"
  ,"synthesis"             = "#AA00FF"
  ,"vesicle"               = "#FF00AA"
)
```

```{r}
abundance_by_function <- cog_size_by_taxid %>%
  inner_join(cog_annotation) %>%
  count(taxid, annotation, wt = cog_size, name = "annotation_count") %>%
  left_join(cog_n_by_taxid) %>%
  left_join(protein_n_by_taxid) %>%
  mutate(
     abundance      = annotation_count / cog_n
    ,abundance_prop = annotation_count / protein_n
  )
```

A
```{r fig.align="center", fig.height=8, fig.width=16, fig.cap="A"}
abundance_by_function %<>% left_join(ordered_species)

metazoa_line <- geom_vline(
   xintercept = "Mnemiopsis leidyi"
  ,color      = "#FF0000"
  ,linetype   = "11"
  ,alpha      = 1
  ,size       = 0.25
)

# This tick function is used in scale_y_continuous
# to only draw 3 middle ticks
tick_function <- function(skip_head = 1, skip_tail = 1) {
  function(x){
    breaks <- seq(x[2], 0, length.out = 5) %>% head(-skip_head) %>% tail(-skip_tail)
    ceiling(breaks/0.25)*0.25
  }
}

ggplot(abundance_by_function) +
  metazoa_line +
  geom_bar(aes(x = ncbi_name, y = abundance, fill = annotation, color = annotation), stat = "identity") +
  facet_grid(annotation ~ clade_name, scales = "free", space = "free_x") +
  scale_y_continuous("Average protein count in neural COGs", breaks = tick_function(), minor_breaks = NULL) +
  xlab("Taxa") +
  scale_fill_manual(values = annotation_colors %>% darken(0.1)) +
  scale_color_manual(values = annotation_colors %>% darken(0.2)) +
  theme(
     panel.spacing      = unit(2.5, "pt")
    ,strip.background.x = element_blank()
    ,strip.background.y = element_rect(fill="#E0E0E0")
    ,panel.grid.major.x = element_blank()
    ,panel.grid.major.y = element_line(colour = "#F5F5F5", size = 0.25)
    ,panel.background   = element_rect(fill = '#EEEEEE', colour = '#E0E0E0')
    ,strip.text.x       = element_text(size = 6, angle = 90, hjust = 0, vjust = 0.5)
    ,strip.text.y       = element_text(size = 8, vjust = 0.5)
    ,axis.text.x        = element_text(size = 2, angle = -45, vjust = 0, hjust = 0)
    ,axis.text.y        = element_text(size = 6)
    ,legend.position    = "none"
  )
ggsave("plots/fig5_raw.pdf", width = 16, height = 8)

# Proportion --------------------
ggplot(abundance_by_function) +
    metazoa_line +
    geom_bar(aes(x = ncbi_name, y = abundance_prop, fill = annotation, color = annotation), stat = "identity") +
    facet_grid(annotation ~ clade_name, scales = "free", space = "free_x") +
    scale_y_continuous( minor_breaks = NULL) +
    scale_fill_manual(values = annotation_colors %>% darken(0.1)) +
    scale_color_manual(values = annotation_colors %>% darken(0.2)) +
    theme(
         panel.spacing      = unit(2.5, "pt")
        ,strip.background.x = element_blank()
        ,strip.background.y = element_rect(fill="#E0E0E0")
        ,panel.grid.major.x = element_blank()
        ,panel.grid.major.y = element_line(colour = "#F5F5F5", size = 0.25)
        ,panel.background   = element_rect(fill = '#EEEEEE', colour = '#E0E0E0')
        ,strip.text.x       = element_text(size = 6, angle = 90, hjust = 0, vjust = 0.5)
        ,strip.text.y       = element_text(size = 8, vjust = 0.5)
        ,axis.text.x        = element_text(size = 2, angle = -45, vjust = 0, hjust = 0)
        ,axis.text.y        = element_text(size = 6)
        ,axis.ticks.x       = element_line(size = 0.1)
        ,legend.position    = "none"
    )
ggsave("plots/fig5_prop_raw.pdf", width = 16, height = 8)
```

A
```{r fig.align="center", fig.height=4, fig.width=5, fig.cap="A"}
ggplot(abundance_by_function) +
  geom_bar(aes(x = clade_name, y = abundance, fill = annotation), stat="summary", fun = "mean") +
  scale_fill_manual(values = annotation_colors, guide = "none") +
  facet_grid(annotation ~ ., scales = "free") +
  theme(
     panel.spacing      = unit(1, "pt")
    ,strip.text.y       = element_text(angle = 0, hjust = 0)
    ,axis.text.x        = element_text(size = 5, angle = -45, vjust = 0, hjust = 0)
    ,axis.text.y        = element_text(size = 5)
  )
```

A
```{r fig.align="center", fig.height=11.69, fig.width=8.27, fig.cap="A"}
# Merging mixed COG functions
cog_annotation_collapsed <- cog_annotation %>%
  group_by(cog_id) %>%
  summarise(annotation = paste(annotation, collapse = "/"))

# Adding colors for mixed COGs
annotation_colors %<>% c(
   "vesicle/synthesis"      = "#808080"
  ,"depletion/vesicle"      = "#808080"
  ,"signaling/excitability" = "#808080"
)

protein_count_by_cog <- cog_size_by_taxid %>%
  inner_join(cog_annotation_collapsed) %>%
  left_join(ordered_species) %>%
  arrange(annotation) %>%
  mutate(cog_id = fct_inorder(cog_id))

ggplot(protein_count_by_cog) +
  metazoa_line + 
  geom_bar(aes(x = ncbi_name, y = cog_size, fill = annotation), stat = "identity") +
  scale_fill_manual(values = annotation_colors %>% darken(0.2), guide = "none") +
  scale_y_continuous(breaks = tick_function(3, 1), minor_breaks = NULL) +
  facet_grid(cog_id ~ ., scales = "free_y") +
  theme(
     panel.spacing      = unit(0.5, "pt")
    ,panel.grid.major.x = element_blank()
    ,panel.grid.major.y = element_line(size = 0.1, linetype = "dashed")
    ,strip.text.y       = element_text(size = 4, angle = 0, hjust = 0)
    ,axis.text.x        = element_text(size = 1.5, angle = -45, vjust = 0, hjust = 0)
    ,axis.text.y        = element_text(size = 4)
    ,axis.ticks         = element_line(size = 0.1)
  )
```
