---
title: "Geneplast"
knit: neurotransmissionevolution::custom_knit
---
```{r message=FALSE, include=FALSE}
knitr::opts_chunk$set(
  warning     = FALSE,
  message     = FALSE#,
  # cache       = TRUE,
  # cache.extra = file.mtime("download/link_pathway_entrez.tsv")
)
library(tidyverse)
library(magrittr)
library(geneplast)
library(ape)
library(XML)
library(rentrez)
library(neurotransmissionevolution)
```

# Dados
Carregamos o arquivo gerados no notebook anterior
```{r rows.print=5}
data(
  cogs,
  cogs_of_interest,
  string_eukaryotes,
  package = "neurotransmissionevolution"
)

cogs %<>% rename(protein_id = string_id, ssp_id = taxid) %>% select(protein_id, ssp_id, cog_id)
```

# Arvore
Gerando objeto phytool da arvore curada
```{r rows.print=5}
# carregando newick
phyloTree <- read.tree("../data/hybrid_tree_modified.nwk") #%>% rotatePhyloTree("9606")

phyloTree %<>% list_modify(
  tip.alias = string_eukaryotes %$% string_name[match(phyloTree[["tip.label"]], taxid)]
)
```

# Geneplast
## Raizes
```{r message=FALSE, warning=FALSE, include=FALSE, quiet=T, eval=T}
ogr <- groot.preprocess(
  cogdata   = cogs,
  phyloTree = phyloTree,
  spid      = "9606",
  cogids    = cogs_of_interest %>% pull(cog_id) %>% unique
)

ogp <- gplast.preprocess(
  cogdata   = cogs,
  cogids    = cogs_of_interest %>% pull(cog_id) %>% unique
)

ogr <- groot(ogr, nPermutations=1)
```
```{r include=F}
# data(ogr, ogp, package = "neurotransmissionevolution")
```

```{r rows.print=5}
roots <- groot.get(ogr, what="results") %>%
  rownames_to_column("cog_id") %>%
  select(cog_id, Root) %>%
  rename(root = Root)

write_tsv(roots, "geneplast_roots.tsv")
```

# extant clades' names
```{r}
lineages <- entrez_fetch(
  db      = "taxonomy",
  id      = string_eukaryotes[["new_taxid"]],
  rettype = "xml",
  retmode = "xml",
  parsed  = TRUE
)

string_eukaryotes %<>% mutate(
  root        = ogr@tree$tip.group[taxid],
  lineage_txt = xpathSApply(lineages, "//Lineage", XML::xmlValue)
)
  
roots_names <- string_eukaryotes %>%
  
  # splitting lienage text
  mutate(lineage_split = strsplit(lineage_txt, "; ")) %>%
  group_by(root) %>%
  
  # for each root, get all lineages intersections
  # but also keep complete lineages for future use
  summarise(lineage = Reduce(intersect, lineage_split) %>% list,
            lineage_list = lineage_split %>% list) %>%
  
  # windowed lineage differences (window size = 3 -> curr, next, prev)
  mutate(downstream_diff = mapply(setdiff,         lineage, lead(lineage))) %>%
  mutate(upstream_diff   = mapply(setdiff, downstream_diff,  lag(lineage))) %>%
  
  # defaults to the furthest rank (i.e. the 1st one)
  mutate(clade_name = map_chr(upstream_diff, 1, .default = NA)) %>%
  
  # finding at what rank depth should mixed lineages be collapsed
  mutate(collapse_depth = lineage %>% map_int(length) + 1) %>%
  
  group_by(root) %>%
  # fallback_name is the collapsed lineage ranks
  mutate(fallback_name = lineage_list %>%
           flatten %>%
           map2_chr(collapse_depth, `[`) %>%
           table %>%
           sort(TRUE) %>%
           # names %>%
           { paste0(names(.), " (", .,")") } %>%
           paste0(collapse="; ")) %>%
  mutate(clade_name = coalesce(clade_name, fallback_name)) %>%
  select(root, clade_name)

write_tsv(roots_names, "temp/temp_geneplast_clade_names.tsv")
```

# plotting all patterns
```{r message=FALSE, include=FALSE}
library(treeio)
library(ggtree)
library(tidytree)
```
```{r}
tree_heatmap <- ogr@orthoct %>%
  as_tibble(rownames = NA) %>%
  select(-1)

phyloTreedata <- phyloTree %>%
  rotatePhyloTree("9606") %>%
  as_tibble %>%
  left_join(string_eukaryotes %>% select(label = taxid, ncbi_name, root)) %>%
  as.treedata

p <- ggtree(phyloTreedata, branch.length = "none", ladderize = F) +
  geom_tiplab(aes(label = ncbi_name), offset = 1, hjust = 0, align = T) +
  xlim(0,300)

gheatmap(
  p,
  tree_heatmap,
  offset=50,
  width=5,
  font.size=2,
  colnames_angle=45,
  hjust=1,
  low = "#DDDDDD",
  high = "#00AA44"
)
```


```{r include=FALSE}
groot.plot(ogr, plot.lcas = TRUE, width=10, height=20, cex.lab = 0.2, cex.nodes = 0.4)

for (i in roots$cog_id) {
  groot.plot(
    ogr, 
    whichOG = i, 
    width=10, 
    height=20, 
    cex.lab = 0.2, 
    cex.nodes = 0.4
  )
}
```

