---
title: "Network"
knit: neurotransmissionevolution::custom_knit
---
```{r include=FALSE}
knitr::opts_chunk$set(
  warning     = FALSE,
  message     = FALSE,
  cache       = TRUE#,
  # cache.extra = file.mtime("download/link_pathway_entrez.tsv")
)
```

### Setting up
Loading resources.
```{r}
# data manipulation
library(tidyverse)
library(igraph)
library(magrittr)

# plotting dependencies
library(scatterpie)
library(UpSetR)
library(gridExtra)
library(patchwork)

# utils
library(neurotransmissionevolution)

data(
  gene_ids,
  gene_cogs,
  gene_pathways,
  string_edgelist,
  pathway_neuroexclusivity,
  package = "neurotransmissionevolution"
)

gene_annotation <- read_tsv("../data/gene_annotation.tsv", col_types = "cc") %>%
  mutate(annotation = case_when(
    grepl("clearance",   annotation) ~ "depletion",
    grepl("degradation", annotation) ~ "depletion",
    grepl("transport",   annotation) ~ "synthesis",
    TRUE ~ annotation
  ))

cog_roots <- read_tsv("geneplast_roots.tsv", col_types = "ci")

roots_extant_clades <- read_tsv("geneplast_clade_names.tsv", col_types = "ic")

pathway_neuroexclusivity    <- read_tsv("neuroexclusivity_pathway.tsv", col_types = "cn")
expression_neuroexclusivity <- read_tsv("neuroexclusivity_expression.tsv", col_types = "cn")
```

Gathering gene data and creating the network graph object.
```{r}
# if a gene has more than 1 COG, select the oldest one.
# this is unusual, but can happen in cases of gene fusion, for instance.
gene_cogs %<>%
  inner_join(cog_roots) %>%
  group_by(string_id) %>%
  filter(root == max(root)) %>%
  inner_join(roots_extant_clades)

# gathering all gene info available
vertices <- gene_ids %>%
  na.omit %>%
  inner_join(gene_pathways) %>%
  inner_join(gene_annotation) %>%
  inner_join(gene_cogs) %>%
  inner_join(pathway_neuroexclusivity) %>%
  mutate(ne = pathway_neuroexclusivity >= 0.9) %>%
  select(string_id, everything())

# quick color hack to aid visualization
vertices %<>%
  unite(color, glutamatergic:dopaminergic, remove = F) %>%
  mutate(color = rainbow(color %>% n_distinct)[color %>% as.factor])

g <- graph_from_data_frame(string_edgelist, directed = F, vertices = vertices)

# setting node sizes
V(g)$size <- V(g)$system_count %>% sqrt %>% multiply_by(5)
```

Generating the network layout (i.e. nodes' coordinates).
```{r}
if(file.exists("network_layout.tsv")) {
  layout <- read_tsv("network_layout.tsv", col_types = "dd") %>% as.matrix
} else {
  layout <- vivagraph(g, precompute_multiplier = 200, precompute_niter = 1000)
}

# inserting layout coordinates into graph object
V(g)$x <-  layout[, 1]
# layout matrix comes vertically flipped
V(g)$y <- -layout[, 2]
```

```{r eval=FALSE, include=FALSE}
# layout %<>% rotate_layout(0)
# 
# layout <- vivagraph(g, layout, repin = T, pinned_cols = 2)
# 
# write_tsv(layout %>% as.data.frame, "layout.tsv")
```

Preparing data for plotting.
```{r}
# recreating the vertices data.frame, now with layout coordinates
vertices <- igraph::as_data_frame(g, what = "vertices") %>% rename(string_id = name)

# the edges data.frame will be used to draw lines with ggplot
edges <- string_edgelist %>%
    map(match, vertices[["string_id"]]) %>%
    map_dfr(~ vertices[.x,]) %>%
    select(x:y) %>%
    cbind(group = 1:nrow(string_edgelist))
```

Setting up reusable aesthetic parameters.
```{r}
pie_colors <- c(
  "cholinergic"   = "#D84315",
  "dopaminergic"  = "#F9A825",
  "gabaergic"     = "#558B2F",
  "glutamatergic" = "#1565C0",
  "serotonergic"  = "#6A1B9A"
)

element_colors <- c(
  "depletion"             = "#F40000",
  "excitability"          = "#FFAB00",
  "receptor-associated"   = "#D6EE00",
  "ionotropic receptor"   = "#43FF1C",
  "metabotropic receptor" = "#18FFFF",
  "signaling"             = "#0091EA",
  "g-protein"             = "#0033ff",
  "synthesis"             = "#AA00FF",
  "vesicle"               = "#FF00AA"
)

systems <- names(pie_colors)

edge_color <- rgb(0.7,0.7,0.7,alpha = 0.3)

past_fill  <- "#FFFFFF"
past_color <- "#888888"

vertices %<>% mutate(
  shape      = ifelse(ne, 22, 21),
  color_node = ifelse(ne, "#000000", element_colors[annotation] %>% darken(0.2)),
  color_pie  = ifelse(ne, "#000000", NA),
)

# reusable ggplot aesthetics
edge_aes <- aes(x = x, y = y, group = group)
text_aes <- aes(x = x, y = y, label = string_name)
pie_aes  <- aes(x = x, y = y, group = string_id, r = size^(0.94) - 1.5)

#xy boundaries
xy_lim <- list(
  scale_x_continuous(limits = range(vertices[["x"]]) + c(-50, 50)),
  scale_y_continuous(limits = range(vertices[["y"]]) + c(-50, 50))
)

diff_theme <- list(
  coord_equal(),
  theme_void(),
  theme(
    plot.title         = element_text(size = 8, hjust = 0.5),
    legend.text        = element_text(size = 6),
    legend.title       = element_text(size = 8),
    legend.key.size    = unit( 1, "mm"),
    legend.box.spacing = unit(-2, "mm"),
    legend.box.margin  = unit(c(0, 2, 0, 0), "mm"),
    plot.margin        = unit(c(0, 0, 0, 0), "mm")
  )
)

roots <- vertices %>% arrange(-root) %>% pull(root) %>% unique
roots_titles <- vertices %>%
  arrange(-root) %>%
  pull(clade_name) %>%
  unique %>%
  paste0(" LCA (", roots, ")")

upset_texts <- c(
  3,   #ytitle
  2,   #ytick
  1,   #setsizetitle
  1.5, #setsizetick
  2,   #setnames
  2.5  #barnums
)
```

### Figure 1

#### Figure 1A
```{r}
# edge lines
plot_edges <- geom_path(data = edges, edge_aes, color = edge_color, size = 0.1)

#piecharts
plot_pies <- geom_scatterpie(data = vertices, pie_aes, cols = systems, color = NA)

# plor scale
plot_pie_fill <- scale_fill_manual(values = pie_colors)

#labels
plot_text <- geom_text(
  data    = vertices,
  text_aes,
  size    = 1,
  vjust   = 0,
  nudge_y = 6,
  alpha   = 0.5
)

# misc
plot_theme <- list(coord_equal(), theme_void())

complete_systems <- ggplot() +
  plot_theme +
  plot_edges +
  plot_pies +
  plot_pie_fill +
  plot_text

complete_systems
  
ggsave("plots/fig1a_raw.pdf", width = 7, height = 7, onefile = F, useDingbats = F)
```

#### Figure 1B
```{r}
plot_nodes <- geom_point(
   data   = vertices
  ,aes(
     x
    ,y
    ,fill  = annotation
    ,color = annotation
    ,size  = size
  ),
   shape  = 21
  ,stroke = 0.5
)

# color and size scales
plot_scales <- list(
   scale_fill_manual(values = element_colors)
  ,scale_color_manual(values = element_colors %>% darken(0.25) %>% setNames(names(element_colors)))
  ,scale_radius(range = c(1.75, 5.00), guide = FALSE)
)
  
complete_functions <- ggplot() +
  plot_theme +
  plot_edges +
  plot_nodes +
  plot_scales +
  plot_text

complete_functions
  
ggsave("plots/fig1b_raw.pdf", width = 7, height = 7, onefile = F, useDingbats = F)
```

### Supplementary Figures 2 and 3 
```{r}
plot_size <- scale_radius(range = c(0.5, 1.3), guide = FALSE)

system_plots   <- list()
function_plots <- list()

walk2(roots, roots_titles, ~ {
  
  #finding which genes should be drawn
  current_genes <- vertices %>% filter(root == .x)
  past_genes    <- vertices %>% filter(root  > .x)
  
  #finding which edges should be drawn
  partial_ids   <- c(current_genes[["string_id"]], past_genes[["string_id"]])
  which_edges   <- apply(string_edgelist, 1, function(r) all(r %in% partial_ids))
  partial_edges <- edges[which_edges,]
  
  ############
  ## COMMON
  ############
  plot_edges <- geom_path(data = partial_edges, edge_aes, color = edge_color, size = 0.1)
  
  plot_past <- geom_point(
     data   = past_genes
    ,aes(
       x
      ,y
      ,size = size
    )
    ,fill   = past_fill
    ,color  = past_color
    ,shape  = past_genes$shape
    ,stroke = 0.25
  )
  
  #labels
  plot_text <- geom_text(
     data    = current_genes
    ,text_aes
    ,size    = 1
    ,vjust   = 0
    ,nudge_y = 1.75
    ,alpha   = 0.5
  )
  
  ############
  ## SYSTEMS
  ############
  plot_current_pies <- geom_scatterpie(
    data  = current_genes,
    pie_aes,
    cols  = systems,
    color = NA
  )
  
  ##############
  ## FUNCTIONS
  ##############
  plot_current_nodes <- geom_point(
     data   = current_genes
    ,aes(
       x
      ,y
      ,fill = annotation
      ,size = size
    )
    ,color  = current_genes$color_node
    ,shape  = current_genes$shape
    ,stroke = 0.25
  )
  
  ############
  ## SAVING
  ############
  base <- ggplot() +
    ggtitle(.y) +
    diff_theme +
    xy_lim +
    plot_edges +
    plot_past +
    plot_size
  
  system_plots[[as.character(.x)]] <<- base +
    plot_current_pies +
    plot_pie_fill +
    plot_text
  
  legend_hack <- guides(fill = guide_legend(override.aes = list(shape = 21)))
  
  function_plots[[as.character(.x)]] <<- base +
    plot_current_nodes +
    plot_scales +
    plot_size +
    plot_text +
    legend_hack
})

#saving pdfs
ggsave(
  "plots/sup_systems_emergence.pdf",
  arrangeGrob(grobs = rev(system_plots), ncol = 3),
  width       = 210,
  height      = 297,
  units       = "mm",
  onefile     = F,
  useDingbats = F
)
ggsave(
  "plots/sup_functions_emergence.pdf",
  arrangeGrob(grobs = rev(function_plots), ncol = 3),
  width       = 210,
  height      = 297,
  units       = "mm",
  onefile     = F,
  useDingbats = F
)
```


### Figure 4
```{r}
idx <- which(roots >= 26 & roots <= 30)

fig4 <- map2(roots[idx], roots_titles[idx], ~ {
  
  #finding which genes should be drawn
  current_genes <- vertices %>% filter(root == .x)
  past_genes    <- vertices %>% filter(root  > .x)
  
  #finding which edges should be drawn
  partial_ids   <- c(current_genes[["string_id"]], past_genes[["string_id"]])
  which_edges   <- apply(string_edgelist, 1, function(r) all(r %in% partial_ids))
  partial_edges <- edges[which_edges,]
  
  ############
  ## COMMON
  ############
  plot_edges <- geom_path(
    data  = partial_edges,
    edge_aes,
    color = edge_color,
    size  = 0.1
  )
  
  plot_past <- geom_point(
    data   = past_genes,
    aes(
      x,
      y,
      size = size
    ),
    fill   = past_fill,
    color  = past_color,
    shape  = past_genes$shape,
    stroke = 0.25
  )
  
  #labels
  plot_text <- geom_text(
    data    = current_genes,
    text_aes,
    size    = 0.8,
    vjust   = -0.5,
    nudge_y = 1,
    alpha   = 0.5
  )
  
  ##############
  ## FUNCTIONS
  ##############
  plot_current_nodes <- geom_point(
    data   = current_genes,
    aes(
       x
      ,y
      ,fill = annotation
      ,size = size
    ),
    color  = current_genes$color_node,
    shape  = current_genes$shape,
    stroke = 0.25
  )
  
  ############
  ## SAVING
  ############
  base <- ggplot() +
    ggtitle(.y) +
    diff_theme +
    xy_lim +
    plot_edges +
    plot_past +
    plot_size
  
  legend_hack <- guides(fill = "none", colour = "none")
  
  base +
    plot_current_nodes +
    plot_scales +
    plot_size +
    plot_text +
    legend_hack
})

ggsave(
  "plots/fig4_raw.pdf",
  arrangeGrob(grobs = fig4, ncol = 5),
  width       = 9*0.8,
  height      = 5*0.8,
  onefile     = F,
  useDingbats = F
)
```

### Figure 3

#### Figure 3A
```{r}
#finding which genes should be drawn
current_genes <- vertices %>% filter(root == 37)

#finding which edges should be drawn
partial_ids   <- current_genes %>% pull(string_id)
which_edges   <- apply(string_edgelist, 1, function(r) all(r %in% partial_ids))
partial_edges <- edges[which_edges,]

############
## COMMON
############
plot_edges <- geom_path(
   data  = partial_edges
  ,edge_aes
  ,color = edge_color
  ,size  = 0.1
)

plot_text <- geom_text(
   data    = current_genes
  ,text_aes
  ,size    = 1
  ,vjust   = 0
  ,nudge_y = 1.75
  ,alpha   = 0.5
)

############
## SYSTEMS
############
plot_current_pies <- geom_scatterpie(
   data  = current_genes
  ,pie_aes
  ,cols  = systems
  ,color = NA
)

############
## SAVING
############
fig3a <- ggplot() +
  plot_edges +
  plot_scales +
  xy_lim +
  plot_current_pies +
  plot_pie_fill +
  plot_text +
  plot_theme

fig3a

ggsave("plots/fig3a_raw.pdf", onefile = F, useDingbats = F, )
```

#### Figure 3B
```{r message=FALSE}
#finding which genes should be drawn
current_genes <- vertices %>% filter(root < 37 & root >= 26)
past_genes    <- vertices %>% filter(root == 37)

#finding which edges should be drawn
partial_ids   <- c(current_genes[["string_id"]], past_genes[["string_id"]])
which_edges   <- apply(string_edgelist, 1, function(r) all(r %in% partial_ids))
partial_edges <- edges[which_edges,]

############
## COMMON
############
plot_edges <- geom_path(data = partial_edges, edge_aes, color = edge_color, size = 0.1)

plot_past <- geom_point(
   data   = past_genes
  ,aes(
     x    = x
    ,y    = y
    ,size = size
  )
  ,fill   = past_fill
  ,color  = past_color
  ,shape  = past_genes$shape
  ,stroke = 0.25
)

#labels
plot_text <- geom_text(
   data    = current_genes
  ,text_aes
  ,size    = 1
  ,vjust   = 0
  ,nudge_y = 1.75
  ,alpha   = 0.5
)

############
## SYSTEMS
############
plot_current_pies <- geom_scatterpie(data = current_genes, pie_aes, cols = systems, color=NA)

############
## SAVING
############
fig3b <- ggplot() +
  plot_edges +
  plot_past +
  plot_scales +
  xy_lim +
  plot_current_pies +
  plot_pie_fill +
  plot_text +
  plot_theme

fig3b

ggsave("plots/fig3b_raw.pdf", onefile = F, useDingbats = F)
```

# upset
```{r}
# we have to manually find the correct color order
# because UpSetR does not understand named vectors
get_colors <- function(df) {
  ordered_systems <- df %>%
    select(systems) %>%
    colSums %>%
    extract(. > 0) %>%
    extract(order(., names(.), decreasing = T))

  pie_colors[names(ordered_systems)]
}

pdf("plots/fig1a_set_raw.pdf",width=18,height=10,onefile=F,useDingbats=FALSE)
  upset(
     vertices %>% select(systems)
    ,mb.ratio        = c(0.7, 0.3)
    ,order.by        = "freq"
    ,mainbar.y.label = "System Intersections"
    ,sets.x.label    = "Genes per system"
    ,text.scale      = upset_texts
    ,point.size      = 3.5
    ,line.size       = 1
    ,sets.bar.color  = get_colors(vertices)
  )
dev.off()

pdf("plots/fig3a_set_raw.pdf",width=16,height=8,onefile=F,useDingbats=FALSE)
  upset(
     vertices %>% filter(root == 37) %>% select(systems)
    ,mb.ratio        = c(0.7, 0.3)
    ,order.by        = "freq"
    ,mainbar.y.label = "System Intersections"
    ,sets.x.label    = "Genes per system"
    ,text.scale      = upset_texts
    ,point.size      = 3.5
    ,line.size       = 1
    ,sets.bar.color  = vertices %>% filter(root == 37) %>% get_colors
  )
dev.off()

pdf("plots/fig3b_set_raw.pdf",width=16,height=8,onefile=F,useDingbats=FALSE)
  upset(
     vertices %>% filter(root < 37 & root >= 26) %>% select(systems)
    ,mb.ratio        = c(0.7, 0.3)
    ,order.by        = "freq"
    ,mainbar.y.label = "System Intersections"
    ,sets.x.label    = "Genes per system"
    ,text.scale      = upset_texts
    ,point.size      = 3.5
    ,line.size       = 1
    ,sets.bar.color  = vertices %>% filter(root < 37 & root >= 26) %>% get_colors
  )
dev.off()
```

