---
title: "Network"
output:
  html_document:
    df_print: paged
    theme: default
    highlight: espresso
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---
# Intro
Obter o layout da rede no RedeR
```{r message=FALSE}
library(XML)
library(rentrez)
library(tidyverse)
library(magrittr)

library(treeio)
library(ggtree)
library(tidytree)
```

# Dados
```{r rows.print=5}
data(
  ogr,
  gene_ids,
  gene_pathways,
  pathway_neuroexclusivity,
  neurotransmission_cogs,
  string_eukaryotes,
  package = "neurotransmission"
)

gene_annotation <- read_tsv("../inst/extdata/gene_annotation.tsv", col_types = "cc") %>%
  mutate(annotation = case_when(
    grepl("clearance",annotation) ~ "depletion",
    grepl("degradation",annotation) ~ "depletion",
    grepl("transport",annotation) ~ "synthesis",
    TRUE ~ annotation
  ))

cog_roots <- read_tsv("../inst/extdata/cogs_roots.tsv", col_types = "ci")
```

# joining data
```{r}
neurotransmission_cogs %<>% inner_join(cog_roots) %>% group_by(string_id) %>% filter(root == max(root))

info <- gene_ids %>%
  na.omit %>%
  inner_join(gene_pathways) %>%
  inner_join(pathway_neuroexclusivity) %>%
  inner_join(gene_annotation) %>%
  inner_join(neurotransmission_cogs) %>%
  mutate(ne = pathway_neuroexclusivity >= 0.9)
```

# wrangle
```{r}
wide_annotation <- info %>%
  mutate(n = 1) %>%
  pivot_wider(
  id_cols = root,
  names_from = annotation,
  values_from = n,
  values_fn = list(n = length),
  values_fill = list(n = 0)
)

ne_count <- info %>%
  group_by(root) %>%
  summarise(n = n(), ne = sum(ne), nne = n() - sum(ne)) %>%
  arrange(-root) %>%
  mutate_at(vars(-root), cumsum) %>%
  pivot_longer(-root, names_to = "annotation", values_to = "n")
  

annotation_cs <- wide_annotation %>%
  arrange(-root) %>%
  mutate_at(vars(-root), cumsum) %>%
  pivot_longer(-root, names_to = "annotation", values_to = "n")
```

# extant clades' names
```{r}
lineages <- entrez_fetch(
  db = "taxonomy",
  id = string_eukaryotes[["new_taxid"]],
  rettype = "xml",
  retmode = "xml",
  parsed=TRUE
)

string_eukaryotes %<>% mutate(
  root = ogr@tree$tip.group[taxid],
  lineage = xpathSApply(lineages, "//Lineage", XML::xmlValue)
)

roots_extant_clades <- string_eukaryotes %>%
  group_by(root) %>%
  summarise(lineage = Reduce(intersect, strsplit(lineage, "; ")) %>% list) %>%
  mutate(extant_name = mapply(setdiff,     lineage, lead(lineage))) %>%
  mutate(extant_name = mapply(setdiff, extant_name,  lag(lineage))) %>%
  mutate(extant_name = map_chr(extant_name, 1, .default = NA)) %>%
  mutate(extant_name = coalesce(extant_name, root %>% as.character, extant_name)) %>%
  select(root, extant_name)

# write_tsv(roots_extant_clades, "extant_clades.tsv")
```

# plot
```{r}
root_text <- roots_extant_clades %>% filter(root %in% ne_count[["root"]])

text <- geom_text(data = root_text, aes(x = root, label = extant_name, y=75), angle=90, hjust=0)
line_aes <- aes(x = root, y = n, group = annotation, color = annotation)
scale_reverse <- scale_x_reverse(breaks = seq(0, 40, by = 1), expand = c(0,0), minor_breaks = NULL)

ggplot(annotation_cs) +
  geom_line(line_aes) +
  scale_reverse +
  text
ggsave("plots/roots_function.pdf", width = 10, height = 6)

ggplot() +
  geom_bar(data = ne_count %>% filter(annotation == "n"), aes(x = root, y = n), fill = "#999999", stat = "identity") +
  geom_line(data = ne_count %>% filter(!annotation == "n"), line_aes, size = 2) +
  scale_reverse +
  text
ggsave("plots/roots_ne.pdf", width = 10, height = 6)
```

```{r message=FALSE}
hybrid_tree <- read.newick("../inst/extdata/hybrid_tree.nwk")

iono_cogs <- info %>% filter(annotation == "ionotropic receptor") %>% pull(cog_id) %>% unique

tree_heatmap <- ogr@orthoct %>%
  as_tibble(rownames = NA) %>%
  select(iono_cogs)

to_drop <- string_eukaryotes %>% filter(!root %in% 29:26) %>% pull(taxid)

early_animals <- hybrid_tree %>%
  drop.tip(to_drop) %>%
  as_tibble %>%
  left_join(string_eukaryotes %>% select(label = taxid, ncbi_name, root)) %>%
  as.treedata
  
p <- ggtree(early_animals, branch.length = "none") +
  geom_tiplab(aes(label = ncbi_name), offset = 1, hjust = 0, align = T) +
  xlim(0,50)

gheatmap(
  p,
  tree_heatmap,
  offset=15,
  width=8,
  font.size=3,
  colnames_angle=45,
  hjust=0.25,
  low = "#DDDDDD",
  high = "#00AA44"
)
ggsave("plots/roots_ionotropic_pattern.pdf", width = 10, height = 6)
```

