---
title: "Network"
output:
  html_document:
    df_print: paged
    theme: default
    highlight: espresso
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---
# Intro
Obter o layout da rede no RedeR
```{r message=FALSE}
library(tidyr)
library(dplyr)
library(readr)
library(magrittr)
library(ggplot2)
```

# Dados
```{r rows.print=5}
data(
  gene_ids,
  gene_pathways,
  # string_edgelist,
  pathway_neuroexclusivity,
  neurotransmission_cogs,
  package = "neurotransmission"
)

gene_annotation <- read_tsv("../inst/extdata/gene_annotation.tsv", col_types = "cc") %>%
  mutate(annotation = case_when(
    grepl("clearance",annotation) ~ "depletion",
    grepl("degradation",annotation) ~ "depletion",
    grepl("g-protein",annotation) ~ "signaling",
    grepl("transport",annotation) ~ "synthesis",
    TRUE ~ annotation
  ))

cog_roots <- read_tsv("../inst/extdata/hybrid_geneplast.tsv")
```

# RedeR
```{r}
neurotransmission_cogs %<>% inner_join(cog_roots) %>% group_by(string_id) %>% filter(hybrid_root == max(hybrid_root))

info <- gene_ids %>%
  na.omit %>%
  inner_join(gene_pathways) %>%
  inner_join(pathway_neuroexclusivity) %>%
  inner_join(gene_annotation) %>%
  inner_join(neurotransmission_cogs) %>%
  mutate(ne = pathway_neuroexclusivity >= 0.9)
```

# wrangle
```{r}
wide_annotation <- info %>%
  mutate(n = 1) %>%
  pivot_wider(
  id_cols = hybrid_root,
  names_from = annotation,
  values_from = n,
  values_fn = list(n = length),
  values_fill = list(n = 0)
)

ne_count <- info %>%
  group_by(hybrid_root) %>%
  summarise(n = n(), ne = sum(ne), nne = n() - sum(ne)) %>%
  arrange(-hybrid_root) %>%
  mutate_at(vars(-hybrid_root), cumsum) %>%
  pivot_longer(-hybrid_root, names_to = "annotation", values_to = "n")
  

annotation_cs <- wide_annotation %>%
  arrange(-hybrid_root) %>%
  mutate_at(vars(-hybrid_root), cumsum) %>%
  pivot_longer(-hybrid_root, names_to = "annotation", values_to = "n")
```

# plot
```{r}
vl <- tribble(
  ~xintercept, ~text,
  29, "Porifera",
  28, "Placozoa",
  27, "Ctenophora",
  26, "Cnidaria"
)

ggplot(annotation_cs) +
  geom_line(aes(x = hybrid_root, y = n, group = annotation, color = annotation)) +
  scale_x_reverse(breaks = seq(0, 40, by = 1), expand = c(0,0), minor_breaks = NULL) +
  geom_vline(data = vl, aes(xintercept = xintercept), alpha = 0.25) +
  geom_text(data = vl, aes(x = xintercept, label = text, y=100), angle=90, hjust=0)
ggsave("cumulative_annotation.pdf", width = 10, height = 6)

ggplot(ne_count) +
  geom_line(aes(x = hybrid_root, y = n, group = annotation, color = annotation)) +
  scale_x_reverse(breaks = seq(0, 40, by = 1), expand = c(0,0), minor_breaks = NULL) +
  geom_vline(data = vl, aes(xintercept = xintercept), alpha = 0.25) +
  geom_text(data = vl, aes(x = xintercept, label = text, y=100), angle=90, hjust=0)
ggsave("cumulative_ne.pdf", width = 10, height = 6)
```

