---
title: "Network"
output:
  html_document:
    df_print: paged
    theme: default
    highlight: espresso
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---
# Intro
Obter o layout da rede no RedeR
```{r message=FALSE}
library(rentrez)
library(tidyverse)
library(magrittr)
library(ggplot2)
```

# Dados
```{r rows.print=5}
data(
  ogr,
  gene_ids,
  neurotransmission_cogs,
  string_eukaryotes,
  package = "neurotransmission"
)

cog_roots <- read_tsv("../inst/extdata/cogs_roots.tsv", col_types = "ci")
```

# wrangle
```{r}
lineages <- entrez_fetch(
  db = "taxonomy",
  id = string_eukaryotes[["new_taxid"]],
  rettype = "xml",
  retmode = "xml",
  parsed=TRUE
)

string_eukaryotes %<>% mutate(
  root = ogr@tree$tip.group[taxid],
  lineage = xpathSApply(lineages, "//Lineage", XML::xmlValue)
)

root_extant <- string_eukaryotes %>%
  group_by(root) %>%
  summarise(lineage = Reduce(intersect, strsplit(lineage, "; ")) %>% list) %>%
  mutate(branch = mapply(setdiff, lineage, lead(lineage))) %>%
  mutate(branch = mapply(setdiff,  branch,  lag(lineage))) %>%
  mutate(branch = map(branch, 1)) %>%
  select(root, branch)
```

# plot
```{r}
vl <- tribble(
  ~xintercept, ~text,
  29, "Porifera",
  28, "Placozoa",
  27, "Ctenophora",
  26, "Cnidaria"
)

ggplot(annotation_cs) +
  geom_line(aes(x = root, y = n, group = annotation, color = annotation)) +
  scale_x_reverse(breaks = seq(0, 40, by = 1), expand = c(0,0), minor_breaks = NULL) +
  geom_vline(data = vl, aes(xintercept = xintercept), alpha = 0.25) +
  geom_text(data = vl, aes(x = xintercept, label = text, y=100), angle=90, hjust=0)
ggsave("roots_function.pdf", width = 10, height = 6)

ggplot() +
  geom_bar(data = ne_count %>% filter(annotation == "n"), aes(x = root, y = n), fill = "#999999", stat = "identity") +
  geom_line(data = ne_count %>% filter(!annotation == "n"), aes(x = root, y = n, group = annotation, color = annotation), size = 2) +
  scale_x_reverse(breaks = seq(0, 40, by = 1), expand = c(0,0), minor_breaks = NULL) +
  geom_vline(data = vl, aes(xintercept = xintercept), alpha = 0.25) +
  geom_text(data = vl, aes(x = xintercept, label = text, y=100), angle=90, hjust=0)
ggsave("roots_ne.pdf", width = 10, height = 6)
```

