---
title: "NCBI geneplast"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    df_print: paged
    highlight: espresso
    number_sections: yes
    theme: default
    toc: yes
    toc_depth: 2
    toc_float: yes
---
# Objetivo
Obter os enraizamentos
```{r}
library(dplyr)
library(readr)
library(tibble)
library(magrittr)
library(geneplast)
library(phytools)
```

# Dados
Carregamos o arquivo gerados no notebook anterior
```{r rows.print=5}
data(
  neurotransmission_cogs,
  cogs,
  string_eukaryotes,
  # ncbi_tree,
  timetree_newick,
  package = "neurotransmission"
)
```

# Arvore
Gerando objeto phytool da arvore curada
```{r rows.print=5}
timetree_newick[["tip.alias"]] <- timetree_newick[["tip.label"]]
timetree_newick[["tip.label"]] <- timetree_newick[["taxid"]]

timetree_newick[["node.label"]] <- NULL
timetree_newick[["edge.length"]] <- NULL
```

Gerando objeto phytool da arvore curada
```{r rows.print=5}
phyloTree <- phytools::read.newick("../inst/extdata/timetree_newick.nwk")

#renomeando tip.alias com base no match entre ssp_ids
phyloTree[["tip.alias"]] <- string_eukaryotes[["string_name"]][match(phyloTree[["tip.label"]], string_eukaryotes[["taxid"]])]
```

# Geneplast
## Raizes
```{r message=F, warning=F, include=FALSE, quiet=T}
cogs %<>% rename(protein_id = string_id, ssp_id = taxid) %>% select(protein_id, ssp_id, cog_id)

ogr <- groot.preprocess(
  cogdata   = cogs,
  phyloTree = timetree_newick,
  spid      = "9606",
  cogids    = neurotransmission_cogs %>% pull(cog_id) %>% unique
) %>%
  groot(nPermutations=2)

ogr2 <- groot.preprocess(
  cogdata   = cogs,
  phyloTree = phyloTree,
  spid      = "9606",
  cogids    = neurotransmission_cogs %>% pull(cog_id) %>% unique
) %>%
  groot(nPermutations=2)
```


```{r rows.print=5}
roots <- groot.get(ogr, what="results")
roots2 <- groot.get(ogr2, what="results")

roots %<>% rownames_to_column("cog_id") %>% select(cog_id, Root) %>% rename(timetree_root = Root)
roots2 %<>% rownames_to_column("cog_id") %>% select(cog_id, Root) %>% rename(timetree_root = Root)

groot.plot(ogr, whichOG="NOG259214", fname="roots1", plot.sspnames = FALSE)
groot.plot(ogr, plot.lcas = TRUE, fname="roots1", plot.sspnames = FALSE)

groot.plot(ogr2, whichOG="NOG259214", fname="roots2", plot.sspnames = FALSE)
groot.plot(ogr2, plot.lcas = TRUE, fname="roots2", plot.sspnames = FALSE)

ogr %>% groot.get("tree") %>% plot(type="cladogram", use.edge.length=F)
ogr2 %>% groot.get("tree") %>% plot(type="cladogram", use.edge.length=F)
# write_tsv(roots, "../inst/extdata/timetree_geneplast.tsv")
```
