---
title: "Network"
output:
  html_document:
    df_print: paged
    theme: default
    highlight: espresso
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---
# Intro
Obter o layout da rede no RedeR
```{r message=FALSE}
library(dplyr)
library(tidyr)
library(readr)
library(igraph)
library(magrittr)
```

# Dados
```{r rows.print=5}
data(
  gene_ids,
  gene_pathways,
  pathway_neuroexclusivity,
  expression_neuroexclusivity,
  string_edgelist,
  package = "neurotransmission"
)

layout <- read_tsv("layout.tsv", col_types = "dd") %>% as.matrix
```

# Position adjustments, rerun as needed
```{r}
# layout %<>% rotate_layout(0)
# 
# layout <- vivagraph(g, layout, repin = T, pinned_cols = 2)
# 
# write_tsv(layout %>% as.data.frame, "layout.tsv")
```

# RedeR
```{r}
vertices <- gene_ids %>%
  na.omit %>%
  inner_join(gene_pathways) %>%
  inner_join(pathway_neuroexclusivity) %>%
  inner_join(expression_neuroexclusivity) %>%
  select(name = string_id, pathway_neuroexclusivity, expression_neuroexclusivity, system_count)

g <- graph_from_data_frame(string_edgelist, directed = F, vertices = vertices)

# removing vesicle cycle-only nodes
g %<>% delete_vertices(which(V(g)$system_count == 0))

V(g)$x <- layout[, 1]
V(g)$y <- layout[, 2]

subgraphs <- decompose.graph(g)
lcc_index <- which.max(sapply(subgraphs, vcount))
lcc <- subgraphs[[lcc_index]]
```

# Force
```{r echo=T, eval=T, include=FALSE}
pajek_nodes <- igraph::as_data_frame(lcc, what = "vertices") %>%
  select(name, signal = pathway_neuroexclusivity, x, y)

pajek_edges <- igraph::as_data_frame(lcc, what = "edges")

hack <- data.frame(
  name = c("top", "bot"),
  signal = 0,
  x = range(pajek_nodes$x) + c(-75, 75),
  y = range(pajek_nodes$y) + c(-75, 75),
  stringsAsFactors = FALSE
)

pajek_nodes %<>% bind_rows(hack) %>% mutate(id = row_number())
```

# Output
```{r}
write("*edges", file="viacomplex_network.net")
write_tsv(pajek_edges, "viacomplex_network.net", append = TRUE, col_names = FALSE, quote_escape = F)
write("*nodes", file="viacomplex_network.net", append = TRUE)
write_tsv(pajek_nodes %>% select(name, x, y), "viacomplex_network.net", append = TRUE, col_names = FALSE, quote_escape = F)

write_tsv(pajek_nodes %>% select(id, name, signal), "viacomplex_kegg.dat")
```

# Force
```{r echo=T, eval=T, include=FALSE}
pajek_nodes <- as_data_frame(lcc, what = "vertices") %>%
  select(name, signal = expression_neuroexclusivity, x, y)

pajek_nodes %<>% bind_rows(hack) %>% mutate(id = row_number())

write_tsv(pajek_nodes %>% select(id, name, signal), "viacomplex_gxa.dat")
```

